name: Detekt Code Review

on:
  pull_request:
    branches: [ main, staging, development ]

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'oracle'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Oracle_jdk/21/x64
          JAVA_HOME_21_X64: /opt/hostedtoolcache/Java_Oracle_jdk/21/x64

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Detekt
        uses: natiginfo/action-detekt-all@1.23.7
        with:
          args: --config detekt/detekt.yml --input src/main/kotlin --excludes buildSrc/.*

#      - name: Run Detekt
#        run: ./gradlew detekt
#
#      - name: Generate Detekt Report
#        if: always() # Ensure this step runs even if previous steps fail
#        uses: actions/upload-artifact@v4
#        with:
#          name: detekt-report
#          path: detekt/reports/detekt.html


#  save-report: # This job is save generated Detekt report to the repository
#    needs: detekt
#    if: always() # Ensure this job runs even if the detekt job fails
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#        with:
#          ref: ${{ github.head_ref }} # Checkout the source branch of the pull request
#
#      - name: Download Detekt report
#        uses: actions/download-artifact@v4
#        with:
#          name: detekt-report
#          path: detekt/reports
#
#      - name: Configure Git
#        run: |
#          git config --global user.name 'github-actions[bot]'
#          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
#
#      - name: Check for changes
#        id: check_changes
#        run: |
#          git add detekt/reports/detekt.html
#          if git diff-index --quiet HEAD --; then
#            echo "No changes to commit"
#            echo "changes=false" >> $GITHUB_OUTPUT
#          else
#            echo "Changes detected"
#            echo "changes=true" >> $GITHUB_OUTPUT
#          fi
#
#      - name: Commit and push Detekt report
#        if: steps.check_changes.outputs.changes == 'true'
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GitHub token to authenticate
#        run: |
#          git commit -m "Add Detekt HTML report"
#          git push origin HEAD:${{ github.head_ref }} # Push to the source branch of the pull request
